FROM maven:3.5-jdk-8-alpine
WORKDIR /app
COPY . /app
RUN mvn install

FROM openjdk:8
WORKDIR /app
COPY --from=1 /app/target/urman.jar /app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "urman.jar"]